"""update lead model2

Revision ID: 427c60225dc5
Revises: 0de7f3d445d2
Create Date: 2026-03-25 11:31:02.871436

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "427c60225dc5"
down_revision: Union[str, Sequence[str], None] = "0de7f3d445d2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. napraw dane
    op.execute("UPDATE leads SET company = '' WHERE company IS NULL")

    # 2. zmień constraint
    op.alter_column("leads", "company", existing_type=sa.VARCHAR(), nullable=False)

    op.alter_column(
        "leads",
        "is_deleted",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("false"),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "leads",
        "is_deleted",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.alter_column("leads", "company", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###
